config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  resources :categories
  resources :articles
  resources :reviews
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
     if user.nil?
        can :read, [Category, Article]
     elsif user.role? "admin"
        can :manage, [Category, Article, Review]
     elsif user.role? "customer"
        can :read, [Category, Article]   
        can [:read, :create], Review
        can [:update, :destroy], Review do |review|
            review.user_id == user.id
        end     
     end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :category
	has_many :reviews
	validates_presence_of :title, :body, :category_id, :publish_date
	validate :publish_date_cannot_be_more_than_30_days
	validate :publish_date_less_than_present_date



	def publish_date_cannot_be_more_than_30_days
		if publish_date.present? && publish_date > Date.today.next_month
			errors.add(:publish_date, "......")
		end
	end

	def publish_date_less_than_present_date
		if publish_date < Date.today
			is_published :enabled

		end
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :articles
	validates_presence_of :name
	validates_uniqueness_of :name
end
	

app/models/permission.rb
class Permission < ApplicationRecord
	belongs_to :user
	belongs_to :role
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :article
	belongs_to :user
	validates_presence_of :body, :article_id, :rating, :user_id, :username
	validates_length_of :body, within: 10...1000
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :permissions
	has_many :users, through: :permissions
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews
	has_many :permissions
	has_many :roles, through: :permissions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of :username, :mobile
  validates_numericality_of :mobile
  validates_length_of :mobile, is:10

  #callback
  after_create :assign_customer_role

  def assign_customer_role
  	Permission.create(user_id: self.id, role_id: Role.last.id)
  end

  def role?(role)
  	self.roles.pluck(:name).include?(role)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?

   rescue_from CanCan::AccessDenied do 
   	   redirect_to root_path, notice: "The page does not exist"

   	
   end

   protected
   def configure_permitted_parameters
   	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :mobile])
   end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
    load_and_authorize_resource #invokes ability class
	
	def index
		@article = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to articles_path
		else
			render action: 'new'
		end
	end

	def show
		@article = Article.find(params[:id])
		@review = Review.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(article_params)
			redirect_to article_path, notice: "Successfully updated"
			
		else
			render action: 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end

	private
	def article_params
		params[:article].permit(:title,:body,:category_id,:publish_date,:feature_image_url,:is_published)
	end

	# def view_article
	# 	@article = Article.find(params.[:id])
	# end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
    load_and_authorize_resource #invokes ability class
	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
	  @category = Category.new(params[:category].permit(:name))
	  if @category.save
		    redirect_to categories_path, notice: "category was successfully created"
	  else
		    render action: 'new'  
	  end
	end

	def show
		@category = Category.find(params[:id])
		@articles = @category.articles
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update_attributes(params[:category].permit(:name))
			redirect_to category_path(@category.id), notice: "The category was successfully updated"
		else
			render action: "edit"
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path, notice: "The category was successfully deleted"

	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :authenticate_user!
	load_and_authorize_resource

	def create
		@review = Review.new(review_params)
        @review.user_id = current_user.id 
        @review.username = current_user.username
		if @review.save
			redirect_to article_path(@review.article_id), notice: "Thank your for adding your review"
		end
	end

	 def destroy 
	 	@review = Review.find(params[:id])
	 	@review.destroy
	 	redirect_to article_path(@review.article_id), notice: "You have successfully deleted the review"

	 end

	private

	def review_params
		params[:review].permit(:body, :rating, :article_id)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
			
	end

	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |a| %>
  
  <% if @article.errors.any? %>
  <h3> These errors prohibited the form from being saved: </h3>
    
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

    
  <% end %>

  <label for="article_category_id">Category ID</label><br>
  <%= a.collection_select :category_id,Category.all, :id, :name,prompt: "Select Category" %> <br><br>

  <label for="article_title">Title : </label><br>
  <%= a.text_field :title %> <span id="titleHandleMsg"></span><br>

  <label for="article_body">Enter your blog here : </label><br>
  <%= a.text_area :body %><br>

  
  <label for="article_published_date">Article Published Date :</label><br>
  <%= a.date_select :publish_date %><br><br>

  <%= a.check_box :is_published %> <label for="is_published">is published</label><br><br>

  <label for="article_image_url">Image URL : </label><br>
  <%= a.text_field :feature_image_url %><br>

  


  <%= a.submit %>
<% end %> 
<script type="text/javascript">
  nameHandle = document.getElementById("article_title")
  titleHandleMsg = document.getElementById("titleHandleMsg")
  nameHandle.addEventListener('focus',function(){
    titleHandleMsg.innerHTML = "Enter the product name";
  },false)
  nameHandle.addEventListener('blur',function(){
    if (nameHandle.value == "") {
      titleHandleMsg.innerHTML = "Name can't be empty"; 
    }
    else{
      titleHandleMsg.innerHTML = "";
    }
    
  },false)

</script>

app/views/articles/edit.html.erb
<h2>Category Product </h2>
 <%= render 'form' %>

app/views/articles/index.html.erb
<h2>Article Details (<%= @article.count %>)</h2>
	
	<h3>Category -  Title - Description  <br/> </h3>
	
	<% @article.each do |a| %>
	
		    <b> <%= a.category.name %> </b>
			<%= a.title %> - 
			<%= a.body %> -
			<%= link_to "view",article_path(a.id) %> <br/>
		    
	
	<% end %>

<br>
<% if (user_signed_in?) && (can? :create, Article.new) %>
<%= link_to "Add Article",new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h2> Add Category </h2>
<%= render 'form' %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
            <%= Category.find(@article.category_id).name %> <br/>
			<%= @article.body %> <br/>
			<%= @article.publish_date %>
			<%= image_tag(@article.feature_image_url, size: "150*150") %> <br/>

			<% if @article.reviews.empty? %>
			   <p> No Reviews found </p>
			<% else %>
			   <h3> Listing reviews </h3>
			   <ol>
			   <% @article.reviews.each do |review| %>
			       <li> <%= review.user.username %> - <%= review.body %> - <%= review.rating %> - <%= review.article_id %> - <%= review.user.email %> 
			       	    <% if (user_signed_in?) && (can? :update, review) %>
			                 <%= link_to "Destroy", review_path(review.id), method: :delete, data: {confirm: "Are you sure you want to delete the review"} %>
			            <% end %>
			          

			       </li>
			<% end %>
			   </ol>
			<% end %>
			<h3> Add your review </h3>	

			<%= form_for @review do |f| %>

			  <label for="review_body"> Body </label> <br/>
			  <%= f.text_area :body %> <br/>
			  <%= f.hidden_field :article_id, value: @article.id %>

			  <label> Rating </label> <br/>
			  <%= f.radio_button :rating, 1 %> *
			  <%= f.radio_button :rating, 2 %> **
			  <%= f.radio_button :rating, 3 %> ***
			  <%= f.radio_button :rating, 4 %> ****
			  <%= f.radio_button :rating, 5 %> ***** <br/>
			  <%= f.submit "Add Review" %>

			<% end %>

			<% if (user_signed_in?) && (can? :update, @article) %>

				<%= link_to "Edit",edit_article_path(@article.id) %>
				<%= link_to "Delete",article_path(@article.id),method: :delete,data: {confirm: "Are you sure ?"} %>

			<% end %>
			

app/views/categories/_form.html.erb
<%= form_for @category  do |f| %>
    <% if @category.errors.any? %>
      <ul>
        <h3> These errors prohibited the form from being saved: </h3>
           <% @category.errors.full_messages.each do |msg| %>
               <li> <%= msg %> </li>
           <% end %>
      </ul>
    <% end %>


<label for = "name"> Name: </label> <span id = "nameMsg">
</span>
<br/>
<%= f.text_field :name %> <br/>

<label for = "description"> Description: </label> <span id = "nameMsg">
</span>
<br/>
<%= f.text_area :description %> <br/>
<%= f.submit %>
<% end %>

<script>
	var  nameHandle = document.getElementById('name');
	var nameMsgHandle = document.getElementById('nameMsg');
    nameHandle.addEventListener('focus',function(){
    	nameMsgHandle.innerHTML = "Enter the category name";
    }, false);

    nameHandle.addEventListener('blur', function(){
    	if(nameHandle.value == ""){
    		nameMsgHandle.innerHTML = "can't be blank";

    	} else {
    		nameMsgHandle.innerHTMl = "";
    	}
    }, false);

</script>

app/views/categories/edit.html.erb
<h2>Category Product </h2>
 <%= render 'form' %>

app/views/categories/index.html.erb
<h2> Categories (<%= @categories.length %>)</h2>
<ol>
	<% @categories.each do |category| %>
	<li>
		<%= link_to category.name, category_path(category.id) %> (<%= category.articles.length %>)
	</li>
	<% end %>
</ol> 
<% if (user_signed_in?) && (can? :update, @article) %>
<%= link_to "Add Category", new_category_path %>
<% end %>

app/views/categories/new.html.erb
<h2> Add Category </h2>
<%= render 'form' %>

app/views/categories/show.html.erb
<h2><%= @category.name %> </h2>
<h3> <%= @category.description %> </h3>
<h4> Listing Articles :- </h4>
<p> <% @articles.each do |article| %>
	 <%= article.title %> <br/>	
	<% end %>

</p>
<p> 
	<% if (user_signed_in?) && (can? :update, @article) %>
		<%= link_to "Edit", edit_category_path(@category.id) %>|
		<%= link_to "Delete", category_path(@category.id), method: :delete,  data: {confirm: "Are you sure?"} %>
	<% end %>
</p>

<br/><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Categories", categories_path %> | <%= link_to "Articles", articles_path %> |
    <% if user_signed_in? %>
          <%= current_user %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %> 
          <b>Welcome <%= current_user.username %></b>
          <%= link_to "Account Setting", edit_user_registration_path %>
    <% else %>
          <%= link_to "Register", new_user_registration_path %> | <%= link_to "Sign in", new_user_session_path %>

    <% end %>
    <%= notice %>
    <%= alert %>
    <%= yield %>
    </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Blog</h1>

app/views/welcome/register.html.erb
 <form class="signupForm">

        <label for="name">Full name</label><br>
        <input class="shortInput" id="name" type="text"><br>

        <label for="email">Email</label><br>
        <input class="shortInput" id="email" type="text"><br>

        <label for="password">Password</label><br>
        <input class="shortInput" id="password" type="text"><br>

        <label for="confirmPassword">Confirm password</label><br>
        <input class="shortInput" id="confirmPassword" type="text"><br>

</form>